### ISSUE TITLE
Compability of DeepRMSD with smina or gnina

### ISSUE THREAD

**Issue by Le-Phung-Hien** [zchwang/DeepRMSD-Vina_Optimization#4]
Hi team,

I am trying DeepRMSD-Vina_Optimization to refine my docking poses. The poses are generated with gnina. Therefore I just wonder if your program can also be used to refine gnina poses?

Also I would like to ask if it is possible to replace the Vina SF with others, such as Vinardo or smina SF, to make a DeepRMSD-smina or DeepRMSD-Vinardo for poses optimization? 

Thank you very much!

**Comment by zchwang** [comment]
Hi,

In theory, this framework can be integrated with other scoring functions, whether deep learning models or traditional empirical potentials. However, the premise of integrating under this framework is that the scoring function needs to be implemented with pytorch and embedded in the entire calculation graph, so that the input terminal is continuously differentiable from the output terminal. Just like in our work, Vina score is re-implemented with pytorch. This is indeed a lot of work. If you just want to use other scoring functions to score poses instead of optimization, just add an additional scoring module.

Best regards
